try:
    from cvxpylayers._version import __version__  # generated by hatch-vcs at build time
except ImportError:
    __version__ = "0.0.0+unknown"

import cvxpylayers._quad_form_dpp  # noqa: F401  # apply monkey-patches at import time
